import Head from 'next/head'
import Header from '../components/Header'
import Brands from '../components/Brands'
import Slider from '../components/Slider'
import MoviesCollection from '../components/MoviesCollection'
import ShowsCollection from '../components/ShowsCollection'



export default function Home() {
  return (
    <div >
      <Head>
        <title>Resumer Pro</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        <Header/>
        <main className="relative min-h-screen after:bg-home after:bg-center after:bg-cover after:bg-no-repeat after:bg-fixed after:absolute after:inset-0 after:z-[-1]">
          <Slider />
        
          <Brands />
          <MoviesCollection />
          <ShowsCollection />
  
             </main>
    </div>
  )
}
